name: Services
favicon: null
layout_spectrum: 0.465817010961473
typography_spectrum: 0.8093590773642063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5046672658063471
  lightness: 0.7669445208739489
  saturation: 0.38518025330267847
  rhythmicContrast: 0.5643597340676934
purpose: []
